// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (id, created_at, updated_at, feed_name, feed_url, created_by_user)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, feed_name, feed_url, created_by_user, last_fetched_at
`

type CreateFeedParams struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	FeedName      string
	FeedUrl       string
	CreatedByUser uuid.UUID
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FeedName,
		arg.FeedUrl,
		arg.CreatedByUser,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeedName,
		&i.FeedUrl,
		&i.CreatedByUser,
		&i.LastFetchedAt,
	)
	return i, err
}

const getFeedByUrl = `-- name: GetFeedByUrl :one

SELECT id, feed_name 
FROM feeds
WHERE feed_url = $1
`

type GetFeedByUrlRow struct {
	ID       uuid.UUID
	FeedName string
}

func (q *Queries) GetFeedByUrl(ctx context.Context, feedUrl string) (GetFeedByUrlRow, error) {
	row := q.db.QueryRowContext(ctx, getFeedByUrl, feedUrl)
	var i GetFeedByUrlRow
	err := row.Scan(&i.ID, &i.FeedName)
	return i, err
}

const getFeedList = `-- name: GetFeedList :many
SELECT feeds.feed_name, feeds.feed_url, created_by_user
FROM feeds
`

type GetFeedListRow struct {
	FeedName      string
	FeedUrl       string
	CreatedByUser uuid.UUID
}

func (q *Queries) GetFeedList(ctx context.Context) ([]GetFeedListRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedListRow
	for rows.Next() {
		var i GetFeedListRow
		if err := rows.Scan(&i.FeedName, &i.FeedUrl, &i.CreatedByUser); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextFeedToFecth = `-- name: GetNextFeedToFecth :one
SELECT id, feed_name, feed_url 
FROM feeds
ORDER BY last_fetched_at ASC NULLS FIRST
LIMIT 1
`

type GetNextFeedToFecthRow struct {
	ID       uuid.UUID
	FeedName string
	FeedUrl  string
}

func (q *Queries) GetNextFeedToFecth(ctx context.Context) (GetNextFeedToFecthRow, error) {
	row := q.db.QueryRowContext(ctx, getNextFeedToFecth)
	var i GetNextFeedToFecthRow
	err := row.Scan(&i.ID, &i.FeedName, &i.FeedUrl)
	return i, err
}

const markFeedFetched = `-- name: MarkFeedFetched :one
UPDATE feeds
SET updated_at = $2, last_fetched_at = $2
WHERE id = $1
RETURNING id, created_at, updated_at, feed_name, feed_url, created_by_user, last_fetched_at
`

type MarkFeedFetchedParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
}

func (q *Queries) MarkFeedFetched(ctx context.Context, arg MarkFeedFetchedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, markFeedFetched, arg.ID, arg.UpdatedAt)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeedName,
		&i.FeedUrl,
		&i.CreatedByUser,
		&i.LastFetchedAt,
	)
	return i, err
}
